version: '3.8'
services:
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:8081
        volumes:
            - ./app/:/app
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
        - 8088:8080