"""Add request

Revision ID: 3b37dce6fc56
Revises: 3dfcd856d2ac
Create Date: 2024-12-29 03:24:51.448219

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b37dce6fc56"
down_revision: Union[str, None] = "3dfcd856d2ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PENDING", "APPROVED", "REJECTED", name="requeststatus").create(
        op.get_bind()
    )
    sa.Enum("DEPOSIT", "WITHDRAW", name="requesttype").create(op.get_bind())
    op.create_table(
        "Requests",
        sa.Column(
            "id",
            sqlmodel.sql.sqltypes.GUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("account_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "DEPOSIT", "WITHDRAW", name="requesttype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="requeststatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["Accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Requests_id"), "Requests", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Requests_id"), table_name="Requests")
    op.drop_table("Requests")
    sa.Enum("DEPOSIT", "WITHDRAW", name="requesttype").drop(op.get_bind())
    sa.Enum("PENDING", "APPROVED", "REJECTED", name="requeststatus").drop(op.get_bind())
    # ### end Alembic commands ###
