"""Add provider email

Revision ID: 5a7633229d03
Revises: 3b37dce6fc56
Create Date: 2024-12-29 03:33:28.376194

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a7633229d03"
down_revision: Union[str, None] = "3b37dce6fc56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Providers",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_foreign_key(None, "Providers", "Emails", ["email"], ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Providers", type_="foreignkey")
    op.drop_column("Providers", "email")
    # ### end Alembic commands ###
