"""Add provider 2

Revision ID: 718afcc0a9ee
Revises: e838ffa1f340
Create Date: 2024-12-28 15:34:52.908586

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "718afcc0a9ee"
down_revision: Union[str, None] = "e838ffa1f340"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "Accounts",
        sa.Column("provider_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
    )
    op.create_foreign_key(None, "Accounts", "Providers", ["provider_id"], ["id"])
    op.add_column(
        "Providers",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Providers", "description")
    op.drop_constraint(None, "Accounts", type_="foreignkey")
    op.drop_column("Accounts", "provider_id")
    # ### end Alembic commands ###
